from typing import Protocol

from app.modules.submissions.domain.entities.submission import Submission


class SubmissionRepository(Protocol):
    async def create(self, submission: Submission) -> Submission: ...

    async def update(self, submission: Submission) -> Submission: ...

    async def list_for_user(self, user_id: str, limit: int, offset: int) -> list[Submission]: ...

    async def list_for_user_level(self, user_id: str, level_id: str) -> list[Submission]: ...

    async def count_for_user_level(self, user_id: str, level_id: str) -> int: ...

    async def get_by_tx_signature(self, tx_signature: str) -> Submission | None: ...
