from __future__ import annotations

from typing import Protocol

from app.modules.levels.domain.entities.level import Level


class LevelRepository(Protocol):
    async def create(self, level: Level) -> Level: ...

    async def get_by_id(self, level_id: str) -> Level | None: ...

    async def get_by_slug(self, slug: str) -> Level | None: ...

    async def get_by_order(self, order: int) -> Level | None: ...

    async def list(self, limit: int, offset: int) -> list[Level]: ...

    async def list_active_vulnerability_levels(self) -> list[Level]: ...
