from typing import Protocol

from app.modules.users.domain.entities.user import User


class UserRepository(Protocol):
    async def create(self, user: User) -> User: ...

    async def get_by_id(self, user_id: str) -> User | None: ...

    async def get_by_email(self, email: str) -> User | None: ...

    async def get_by_username(self, username: str) -> User | None: ...

    async def list(self, limit: int, offset: int) -> list[User]: ...

    async def update(self, user: User) -> User: ...
